<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFvyq6og\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFvyq6og/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFvyq6og.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFvyq6og\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFvyq6og\appProdProjectContainer([
    'container.build_hash' => 'Fvyq6og',
    'container.build_id' => 'c68b9c4f',
    'container.build_time' => 1616824093,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFvyq6og');
